name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x chat/gradlew

    - name: Move into the Gradle project directory
      run: cd Chat && ./gradlew build --no-daemon

    - name: Update dependency graph
      uses: gradle/actions/dependency-submission@v3
